# -*- coding: utf-8 -*-
"""ciciot_2023_h_cnn_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBOD9vGh3s1ekKiBd6t5v8jUUYdPDAh2
"""

# =========================
# Colab-friendly Settings
# =========================
import os
import sys
import json
from pathlib import Path

IS_COLAB = "google.colab" in sys.modules

SEED = 2025

# Device
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("torch:", torch.__version__)
print("cuda:", torch.cuda.is_available(), "| device:", device)
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))

# -------- Training config (先保守，避免 Colab OOM) --------
LR_B = 1e-2
LR_T = 1e-3

BATCH_B = 256
BATCH_T = 256

EPOCHS_B = 10
EPOCHS_T = 100
PATIENCE = 20
S2_LABEL_SMOOTH = 0.0

LSTM_HIDDEN = 128
LSTM_LAYERS = 2
LSTM_BIDIR = True

DROPOUT = 0.5
GRAD_CLIP = 1.0
SEQ_LEN = 32
STRIDE = 1

# -------- Run config --------
RUN_TAG = "colab_cicids2017_h_cnn_lstm_v1"
SAVE_RUN_REPORT = True

# Data prep only
CICIDS_PREP_ONLY = True

# Keep this < 1.0 on low-RAM Colab.
CICIDS_SAMPLE_FRAC_PER_FILE = 1.0
# Set to a positive int for quick debug; None means full file.
CICIDS_NROWS_PER_FILE = None
CICIDS_FILE_GLOB = "*.csv"

# Base paths
BASE_DIR = Path("/content")
CKPT_DIR = Path("/content/checkpoints")
CKPT_DIR.mkdir(parents=True, exist_ok=True)

# DataLoader options (0 is safer for low-RAM Colab)
NUM_WORKERS = 0
PIN_MEMORY = torch.cuda.is_available()

if IS_COLAB:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)

DATA_ROOT = Path("/content/drive/MyDrive/dataset/CICIDS2017")

import gc
import re
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler


def read_cicids_csv(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path, low_memory=False, nrows=CICIDS_NROWS_PER_FILE)
    df.columns = df.columns.str.strip()
    if "label" in df.columns and "Label" not in df.columns:
        df = df.rename(columns={"label": "Label"})
    if " Label" in df.columns and "Label" not in df.columns:
        df = df.rename(columns={" Label": "Label"})
    assert "Label" in df.columns, f"No Label column in {csv_path}"
    return df


CICIDS_FILES = [
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Tuesday-WorkingHours.pcap_ISCX.csv",
    "Wednesday-WorkingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv",
    "Friday-WorkingHours-Morning.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
]

all_csv = list(DATA_ROOT.glob("*.csv"))
name_to_path = {p.name.lower(): p for p in all_csv}
csv_files = []
missing = []
for fname in CICIDS_FILES:
    p = name_to_path.get(fname.lower())
    if p is None:
        missing.append(fname)
    else:
        csv_files.append(p)

assert not missing, f"Missing CICIDS files: {missing}"
print(f"[CICIDS2017] Using csv files: {len(csv_files)}")
print("  first:", csv_files[0].name, "| last:", csv_files[-1].name)

# Low-RAM streaming config (recommended for Colab 12GB).
LOW_RAM_CHUNK_MODE = True
CICIDS_CHUNK_SIZE = 120_000
MAX_ROWS_TRAIN = 800_000
MAX_ROWS_VAL = 200_000
MAX_ROWS_TEST = 200_000


# =========================
# 3A) Label mapping + targets
# =========================
import torch

SEED = 2025
np.random.seed(SEED)
torch.manual_seed(SEED)

if "NUM_WORKERS" not in globals():
    NUM_WORKERS = 2
if "PIN_MEMORY" not in globals():
    PIN_MEMORY = torch.cuda.is_available()
if "BATCH_B" not in globals():
    BATCH_B = 128
if "BATCH_T" not in globals():
    BATCH_T = 128

ATTACK7_NAMES = ["DoS", "DDoS", "BruteForce", "WebAttack", "Botnet", "PortScan"]
FAMILY_NAMES = ["Normal"] + ATTACK7_NAMES
FAMILY_TO_ID = {k: i for i, k in enumerate(FAMILY_NAMES)}
ATTACK7_TO_ID = {k: i for i, k in enumerate(ATTACK7_NAMES)}


def _normalize_label(s: str) -> str:
    x = str(s).strip().lower().replace("_", " ").replace("-", " ")
    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()
    return x


def _map_to_family(raw_label: str) -> str:
    x = _normalize_label(raw_label)
    if "benign" in x:
        return "Normal"
    # Check DDoS before DoS because "ddos" contains "dos".
    if "ddos" in x:
        return "DDoS"
    if ("dos" in x) or ("hulk" in x) or ("goldeneye" in x) or ("slowloris" in x) or ("slowhttptest" in x):
        return "DoS"
    if "patator" in x:
        return "BruteForce"
    if "web attack" in x or "sql injection" in x or "xss" in x:
        return "WebAttack"
    if "bot" in x:
        return "Botnet"
    if "portscan" in x or "port scan" in x:
        return "PortScan"
    # Explicitly excluded per experiment design.
    if "heartbleed" in x or "infiltration" in x:
        return "Unknown"
    return "Unknown"


def add_targets(df: pd.DataFrame, verbose: bool = True) -> pd.DataFrame:
    out = df.copy()
    out.columns = out.columns.str.strip()
    if "label" in out.columns and "Label" not in out.columns:
        out = out.rename(columns={"label": "Label"})
    if " Label" in out.columns and "Label" not in out.columns:
        out = out.rename(columns={" Label": "Label"})
    assert "Label" in out.columns, "No Label column found."

    out["Label_raw"] = out["Label"].astype(str)
    out["Family"] = out["Label_raw"].map(_map_to_family)

    unknown_n = int((out["Family"] == "Unknown").sum())
    if verbose and unknown_n > 0:
        print(f"[warn] drop unknown labels: {unknown_n}")
    out = out[out["Family"] != "Unknown"].reset_index(drop=True)

    out["y_bin"] = (out["Family"] != "Normal").astype(np.int64)
    out["y_family"] = out["Family"].map(FAMILY_TO_ID).astype(np.int64)

    out["y_attack7"] = np.int64(-1)
    m = out["Family"] != "Normal"
    out.loc[m, "y_attack7"] = out.loc[m, "Family"].map(ATTACK7_TO_ID).astype(np.int64)
    return out


def iter_cicids_chunks(csv_path: Path, chunksize: int):
    reader = pd.read_csv(
        csv_path,
        low_memory=False,
        chunksize=chunksize,
        nrows=CICIDS_NROWS_PER_FILE,
    )
    for ch in reader:
        ch.columns = ch.columns.str.strip()
        if "label" in ch.columns and "Label" not in ch.columns:
            ch = ch.rename(columns={"label": "Label"})
        if " Label" in ch.columns and "Label" not in ch.columns:
            ch = ch.rename(columns={" Label": "Label"})
        if "Label" not in ch.columns:
            continue
        if 0.0 < CICIDS_SAMPLE_FRAC_PER_FILE < 1.0:
            n_keep = max(1, int(len(ch) * CICIDS_SAMPLE_FRAC_PER_FILE))
            ch = ch.sample(n=n_keep, random_state=42)
        yield ch


def split_chunk_stratified(df_chunk: pd.DataFrame, rng: np.random.Generator):
    tr_parts, va_parts, te_parts = [], [], []
    for _, g in df_chunk.groupby("Family", sort=False):
        n = len(g)
        if n <= 2:
            tr_parts.append(g)
            continue
        idx = np.arange(n)
        rng.shuffle(idx)
        n_tr = int(round(n * 0.70))
        n_va = int(round(n * 0.15))
        n_tr = min(max(1, n_tr), n - 1)
        n_va = min(max(0, n_va), n - n_tr)
        n_te = n - n_tr - n_va
        if n_te < 0:
            n_te = 0
        g2 = g.iloc[idx]
        tr_parts.append(g2.iloc[:n_tr])
        if n_va > 0:
            va_parts.append(g2.iloc[n_tr:n_tr + n_va])
        if n_te > 0:
            te_parts.append(g2.iloc[n_tr + n_va:])
    df_tr = pd.concat(tr_parts, axis=0, ignore_index=True) if tr_parts else pd.DataFrame()
    df_va = pd.concat(va_parts, axis=0, ignore_index=True) if va_parts else pd.DataFrame()
    df_te = pd.concat(te_parts, axis=0, ignore_index=True) if te_parts else pd.DataFrame()
    return df_tr, df_va, df_te


def append_with_cap(df_base: pd.DataFrame, df_new: pd.DataFrame, cap: int):
    if df_new is None or len(df_new) == 0:
        return df_base
    if df_base is None or len(df_base) == 0:
        out = df_new
    else:
        out = pd.concat([df_base, df_new], axis=0, ignore_index=True)
    if (cap is not None) and (len(out) > cap):
        out = out.sample(n=cap, random_state=42).reset_index(drop=True)
    return out


rng = np.random.default_rng(42)
df_train, df_val, df_test = None, None, None
raw_rows = 0
kept_rows = 0

for p in csv_files:
    print(f"[stream] {p.name}")
    for chunk in iter_cicids_chunks(p, CICIDS_CHUNK_SIZE):
        raw_rows += len(chunk)
        chunk = add_targets(chunk, verbose=False)
        kept_rows += len(chunk)
        if len(chunk) == 0:
            continue
        tr_c, va_c, te_c = split_chunk_stratified(chunk, rng)
        df_train = append_with_cap(df_train, tr_c, MAX_ROWS_TRAIN)
        df_val = append_with_cap(df_val, va_c, MAX_ROWS_VAL)
        df_test = append_with_cap(df_test, te_c, MAX_ROWS_TEST)

print(f"[CICIDS2017] streamed rows(raw): {raw_rows:,} | kept(after map/drop): {kept_rows:,}")
assert df_train is not None and len(df_train) > 0, "Empty train split after streaming."
assert df_val is not None and len(df_val) > 0, "Empty val split after streaming."
assert df_test is not None and len(df_test) > 0, "Empty test split after streaming."
print("Before clean:", len(df_train), len(df_val), len(df_test))
print("Train family (before clean):\n", df_train["Family"].value_counts())


# =========================
# 3B) Cleaning + numeric features + scaling
# =========================
# Optional quick downsampling for Colab debug.
USE_SUBSAMPLE = False
SUBSAMPLE_TRAIN_N = 800_000
SUBSAMPLE_VAL_N = 200_000
SUBSAMPLE_TEST_N = 200_000

META_DROP_CANDIDATES = ["Flow ID", "Source IP", "Destination IP", "Timestamp"]
TARGET_COLS = ["Label", "Label_raw", "Family", "y_bin", "y_family", "y_attack7"]


def _optional_subsample(df: pd.DataFrame, n: int, name: str) -> pd.DataFrame:
    if (not USE_SUBSAMPLE) or (len(df) <= n):
        return df
    out = df.groupby("Family", group_keys=False).apply(
        lambda g: g.sample(max(1, int(round(len(g) * n / len(df)))), random_state=SEED)
    ).reset_index(drop=True)
    if len(out) > n:
        out = out.sample(n=n, random_state=SEED).reset_index(drop=True)
    print(f"[{name}] subsample: {len(df):,} -> {len(out):,}")
    return out


def clean_split(df: pd.DataFrame, name: str):
    before = len(df)
    df = df.drop_duplicates().reset_index(drop=True)
    dup_removed = before - len(df)

    drop_cols = [c for c in META_DROP_CANDIDATES if c in df.columns]
    if drop_cols:
        df = df.drop(columns=drop_cols)

    raw_feature_cols = [c for c in df.columns if c not in TARGET_COLS]

    # Convert to numeric; non-numeric columns become NaN and are dropped if fully invalid.
    num_df = df[raw_feature_cols].apply(pd.to_numeric, errors="coerce")
    valid_feature_cols = [c for c in num_df.columns if num_df[c].notna().any()]
    num_df = num_df[valid_feature_cols]

    arr = num_df.to_numpy(dtype=np.float64)
    finite_mask = np.isfinite(arr).all(axis=1)
    cleaned = df.loc[finite_mask].reset_index(drop=True)
    X = num_df.loc[finite_mask].to_numpy(dtype=np.float32)

    y_bin = cleaned["y_bin"].to_numpy(dtype=np.int64)
    y_attack = cleaned["y_attack7"].to_numpy(dtype=np.int64)

    removed = int((~finite_mask).sum())
    print(
        f"[{name}] rows={before:,} | dup_removed={dup_removed:,} | nan_inf_removed={removed:,} | kept={len(cleaned):,}"
    )
    print(f"[{name}] feature_dim={X.shape[1]}")

    return cleaned, X, y_bin, y_attack, valid_feature_cols


# Optional downsample before cleaning (for speed only).
df_train = _optional_subsample(df_train, SUBSAMPLE_TRAIN_N, "train")
df_val = _optional_subsample(df_val, SUBSAMPLE_VAL_N, "val")
df_test = _optional_subsample(df_test, SUBSAMPLE_TEST_N, "test")

# Clean each split independently (no leakage).
df_train, X_train, y_train_bin, y_train_attack7, feature_cols_train = clean_split(df_train, "train")
df_val, X_val, y_val_bin, y_val_attack7, feature_cols_val = clean_split(df_val, "val")
df_test, X_test, y_test_bin, y_test_attack7, feature_cols_test = clean_split(df_test, "test")

# Keep intersection to ensure identical schema.
feature_cols = [
    c for c in feature_cols_train
    if (c in set(feature_cols_val)) and (c in set(feature_cols_test))
]
feature_cols = sorted(feature_cols)
assert len(feature_cols) > 0, "No common numeric feature columns across train/val/test"

X_train = df_train[feature_cols].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=np.float32)
X_val = df_val[feature_cols].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=np.float32)
X_test = df_test[feature_cols].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=np.float32)

# Safety: by construction should be finite; enforce anyway.
mask_tr = np.isfinite(X_train).all(axis=1)
mask_va = np.isfinite(X_val).all(axis=1)
mask_te = np.isfinite(X_test).all(axis=1)
X_train, y_train_bin, y_train_attack7 = X_train[mask_tr], y_train_bin[mask_tr], y_train_attack7[mask_tr]
X_val, y_val_bin, y_val_attack7 = X_val[mask_va], y_val_bin[mask_va], y_val_attack7[mask_va]
X_test, y_test_bin, y_test_attack7 = X_test[mask_te], y_test_bin[mask_te], y_test_attack7[mask_te]

# Train-only fit scaler.
scaler = MinMaxScaler()
scaler.fit(X_train)

X_train_s = scaler.transform(X_train).astype(np.float32)
X_val_s = scaler.transform(X_val).astype(np.float32)
X_test_s = scaler.transform(X_test).astype(np.float32)

print("X_train_s:", X_train_s.shape, "X_val_s:", X_val_s.shape, "X_test_s:", X_test_s.shape)
print("train bin counts:", np.bincount(y_train_bin, minlength=2))
print("train attack counts:", np.bincount(y_train_attack7[y_train_attack7 >= 0], minlength=len(ATTACK7_NAMES)))
del df_train, df_val, df_test
gc.collect()

# =========================
# 3C) Sequence + DataLoader (lazy windows, low RAM)
# =========================
SEQ_LEN = 32
STRIDE_TRAIN = 1
STRIDE_EVAL = 1


def build_end_indices(n_rows: int, seq_len: int, stride: int) -> np.ndarray:
    if n_rows < seq_len:
        raise ValueError(f"N={n_rows} < seq_len={seq_len}")
    return np.arange(seq_len - 1, n_rows, stride, dtype=np.int64)


train_end_idx = build_end_indices(len(X_train_s), SEQ_LEN, STRIDE_TRAIN)
val_end_idx = build_end_indices(len(X_val_s), SEQ_LEN, STRIDE_EVAL)
test_end_idx = build_end_indices(len(X_test_s), SEQ_LEN, STRIDE_EVAL)

y_train_bin_seq = y_train_bin[train_end_idx]
y_val_bin_seq = y_val_bin[val_end_idx]
y_test_bin_seq = y_test_bin[test_end_idx]

y_train_attack7_seq = y_train_attack7[train_end_idx]
y_val_attack7_seq = y_val_attack7[val_end_idx]
y_test_attack7_seq = y_test_attack7[test_end_idx]

train_atk_mask = (y_train_attack7_seq >= 0)
val_atk_mask = (y_val_attack7_seq >= 0)
test_atk_mask = (y_test_attack7_seq >= 0)

train_end_idx_atk = train_end_idx[train_atk_mask]
val_end_idx_atk = val_end_idx[val_atk_mask]
test_end_idx_atk = test_end_idx[test_atk_mask]

y_train_atk_seq = y_train_attack7_seq[train_atk_mask]
y_val_atk_seq = y_val_attack7_seq[val_atk_mask]
y_test_atk_seq = y_test_attack7_seq[test_atk_mask]


class WindowDataset(Dataset):
    def __init__(self, X: np.ndarray, end_idx: np.ndarray, y: np.ndarray, seq_len: int):
        self.X = X
        self.end_idx = end_idx.astype(np.int64)
        self.y = y.astype(np.int64)
        self.seq_len = int(seq_len)

    def __len__(self):
        return len(self.end_idx)

    def __getitem__(self, i):
        e = int(self.end_idx[i])
        s = e - self.seq_len + 1
        xw = self.X[s:e + 1]  # (L, F)
        return torch.from_numpy(xw).float().transpose(0, 1), torch.tensor(self.y[i], dtype=torch.long)


def make_loader_from_end_idx(X, end_idx, y, batch_size, shuffle):
    ds = WindowDataset(X, end_idx, y, SEQ_LEN)
    return DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
    )


def make_weighted_loader_from_end_idx(X, end_idx, y, batch_size):
    y = np.asarray(y, dtype=np.int64)
    n_classes = int(y.max()) + 1
    counts = np.bincount(y, minlength=n_classes).astype(np.float32)
    counts = np.maximum(counts, 1.0)
    class_w = 1.0 / np.sqrt(counts)
    sample_w = class_w[y]

    ds = WindowDataset(X, end_idx, y, SEQ_LEN)
    sampler = WeightedRandomSampler(
        weights=torch.from_numpy(sample_w).double(),
        num_samples=len(sample_w),
        replacement=True,
    )
    return DataLoader(
        ds,
        batch_size=batch_size,
        sampler=sampler,
        num_workers=NUM_WORKERS,
        pin_memory=PIN_MEMORY,
    )


# Loaders for NN attack classifier.
atk_train_loader = make_weighted_loader_from_end_idx(X_train_s, train_end_idx_atk, y_train_atk_seq, BATCH_T)
atk_val_loader = make_loader_from_end_idx(X_val_s, val_end_idx_atk, y_val_atk_seq, BATCH_T, False)
atk_test_loader = make_loader_from_end_idx(X_test_s, test_end_idx_atk, y_test_atk_seq, BATCH_T, False)

# Full-sequence loaders (all windows) for attack-prob inference in hierarchical step.
full_val_loader = make_loader_from_end_idx(X_val_s, val_end_idx, y_val_bin_seq, BATCH_T, False)
full_test_loader = make_loader_from_end_idx(X_test_s, test_end_idx, y_test_bin_seq, BATCH_T, False)

print("Window counts (all):", len(train_end_idx), len(val_end_idx), len(test_end_idx))
print("Window counts (atk):", len(train_end_idx_atk), len(val_end_idx_atk), len(test_end_idx_atk))
print("Bin counts train:", np.bincount(y_train_bin_seq, minlength=2))
print("Attack counts train:", np.bincount(y_train_atk_seq, minlength=len(ATTACK7_NAMES)))
print("Ready: atk_*_loader + full_*_loader")

import torch
import torch.nn as nn

class CNNLSTMHybrid(nn.Module):
    def __init__(self, in_ch: int, n_classes: int, lstm_hidden=128, lstm_layers=2, bidir=True, dropout=0.5):
        super().__init__()
        self.block1 = nn.Sequential(
            nn.Conv1d(in_ch, 64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.MaxPool1d(2),
            nn.Dropout(dropout),
        )
        self.block2 = nn.Sequential(
            nn.Conv1d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.MaxPool1d(2),
            nn.Dropout(dropout),
        )
        self.block3 = nn.Sequential(
            nn.Conv1d(128, 256, kernel_size=3, padding=1),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.MaxPool1d(2, ceil_mode=True),
            nn.Dropout(dropout),
        )

        self.bidir = bidir
        self.lstm = nn.LSTM(
            input_size=256,
            hidden_size=lstm_hidden,
            num_layers=lstm_layers,
            batch_first=True,
            dropout=dropout if lstm_layers > 1 else 0.0,
            bidirectional=bidir,
        )
        lstm_out = lstm_hidden * (2 if bidir else 1)

        self.fc = nn.Sequential(
            nn.Linear(lstm_out, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, n_classes),
        )

    def forward(self, x):
        # x: (B, F, L)
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)          # (B, 256, L')
        x = x.transpose(1, 2)       # (B, L', 256)
        x, _ = self.lstm(x)         # (B, L', H)
        x = x[:, -1, :]             # last step
        return self.fc(x)

# ===== 4) Training (XGBoost Gate + CNN-LSTM Attack) =====
import copy
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score, f1_score

try:
    from xgboost import XGBClassifier
except Exception as e:
    raise ImportError("xgboost is required for stage-1 gate. Please install xgboost in Colab.") from e

# ---------- Config ----------
LR_ATK = globals().get("LR_ATK", 1e-3)
EPOCHS_ATK = globals().get("EPOCHS_ATK", 12)
PATIENCE = globals().get("PATIENCE", 4)
GRAD_CLIP = globals().get("GRAD_CLIP", 1.0)
DROPOUT = globals().get("DROPOUT", 0.5)
LSTM_HIDDEN = globals().get("LSTM_HIDDEN", 128)
LSTM_LAYERS = globals().get("LSTM_LAYERS", 2)
LSTM_BIDIR = globals().get("LSTM_BIDIR", True)

GATE_TARGET_DR = 0.90
GATE_TARGET_FPR = 0.03


def binary_metrics(y_true_bin, y_pred_bin):
    y_true_bin = y_true_bin.astype(np.int64)
    y_pred_bin = y_pred_bin.astype(np.int64)
    tp = int(((y_true_bin == 1) & (y_pred_bin == 1)).sum())
    fn = int(((y_true_bin == 1) & (y_pred_bin == 0)).sum())
    fp = int(((y_true_bin == 0) & (y_pred_bin == 1)).sum())
    tn = int(((y_true_bin == 0) & (y_pred_bin == 0)).sum())
    dr = tp / (tp + fn + 1e-12)
    fpr = fp / (fp + tn + 1e-12)
    acc = (y_true_bin == y_pred_bin).mean()
    return {"DR": dr, "FPR": fpr, "ACC": acc, "tp": tp, "fn": fn, "fp": fp, "tn": tn}


def compute_class_weights(y: np.ndarray, n_classes: int, mode="sqrt", cap=None):
    c = np.bincount(y, minlength=n_classes).astype(np.float32)
    c = np.maximum(c, 1.0)
    if mode == "none":
        w = np.ones(n_classes, dtype=np.float32)
    elif mode == "linear":
        w = 1.0 / c
    else:
        w = np.sqrt(1.0 / c)
    if cap is not None:
        w = np.minimum(w, w.min() * cap)
    w = w / w.sum() * n_classes
    return torch.tensor(w, dtype=torch.float32), c.astype(np.int64)


@torch.no_grad()
def eval_loss(model, loader, criterion):
    model.eval()
    total, n = 0.0, 0
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        loss = criterion(model(xb), yb)
        total += loss.item() * yb.size(0)
        n += yb.size(0)
    return total / max(1, n)


def train_attack_model(model, train_loader, val_loader, criterion, lr, epochs, patience):
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs, eta_min=1e-5)

    best_state = None
    best_val = float("inf")
    wait = 0

    for ep in range(1, epochs + 1):
        model.train()
        total, n = 0.0, 0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            opt.zero_grad(set_to_none=True)
            loss = criterion(model(xb), yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP)
            opt.step()
            total += loss.item() * yb.size(0)
            n += yb.size(0)

        sch.step()
        tr = total / max(1, n)
        va = eval_loss(model, val_loader, criterion)
        is_best = va < best_val

        if is_best:
            best_val = va
            best_state = copy.deepcopy(model.state_dict())
            wait = 0
        else:
            wait += 1

        print(f"[ATK] ep={ep:02d} train={tr:.5f} val={va:.5f}" + (" *best" if is_best else ""))

        if wait >= patience:
            print(f"[ATK] early stop at ep={ep}, best_val={best_val:.5f}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)
    return model, best_val


# =========================
# 4A) Stage-1: XGBoost Binary Gate (row-level)
# =========================
print("\n[4A] Train gate model: XGBoost binary gate")

n_neg = int((y_train_bin == 0).sum())
n_pos = int((y_train_bin == 1).sum())
scale_pos_weight = float(n_neg / max(1, n_pos))

print(f"  train bin counts: normal={n_neg:,}, attack={n_pos:,}, scale_pos_weight={scale_pos_weight:.4f}")

gate_model = XGBClassifier(
    objective="binary:logistic",
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_lambda=1.0,
    random_state=SEED,
    tree_method="hist",
    eval_metric="logloss",
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight,
)

gate_model.fit(X_train_s, y_train_bin)

val_prob = gate_model.predict_proba(X_val_s)[:, 1]
val_pred = (val_prob >= 0.5).astype(np.int64)
val_gate_m = binary_metrics(y_val_bin, val_pred)
print(
    f"[4A] val @0.5 | DR={val_gate_m['DR']*100:.2f}% | "
    f"FPR={val_gate_m['FPR']*100:.2f}% | ACC={val_gate_m['ACC']*100:.2f}%"
)

# =========================
# 4B) Stage-2 class weights (sqrt + cap=15)
# =========================
print("\n[4B] Build class weights for attack classifier")

N_ATTACK = len(ATTACK7_NAMES)
cw_atk, cnt_atk = compute_class_weights(y_train_atk_seq, n_classes=N_ATTACK, mode="sqrt", cap=15.0)
print("  attack counts:", cnt_atk.tolist())
print("  attack weights:", cw_atk.numpy().tolist())

# =========================
# 4C) Stage-2: CNN-LSTM Attack Classifier
# =========================
print("\n[4C] Train attack model: CNN-LSTM")

in_ch = X_train_s.shape[1]
atk_model = CNNLSTMHybrid(
    in_ch=in_ch,
    n_classes=N_ATTACK,
    lstm_hidden=LSTM_HIDDEN,
    lstm_layers=LSTM_LAYERS,
    bidir=LSTM_BIDIR,
    dropout=DROPOUT,
).to(device)

criterion_atk = nn.CrossEntropyLoss(weight=cw_atk.to(device), label_smoothing=0.0)
atk_model, best_atk_val = train_attack_model(
    atk_model,
    atk_train_loader,
    atk_val_loader,
    criterion_atk,
    lr=LR_ATK,
    epochs=EPOCHS_ATK,
    patience=PATIENCE,
)
print(f"[4C] best_atk_val={best_atk_val:.5f}")

# =========================
# 4D) Save models (1: gate, 2: attack)
# =========================
gate_model_path = CKPT_DIR / f"{RUN_TAG}_gate_xgb.json"
atk_model_path = CKPT_DIR / f"{RUN_TAG}_attack_cnnlstm.pth"

gate_model.save_model(str(gate_model_path))
torch.save(
    {
        "state_dict": atk_model.state_dict(),
        "in_ch": int(in_ch),
        "n_classes": int(N_ATTACK),
        "lstm_hidden": int(LSTM_HIDDEN),
        "lstm_layers": int(LSTM_LAYERS),
        "lstm_bidir": bool(LSTM_BIDIR),
        "dropout": float(DROPOUT),
        "seq_len": int(SEQ_LEN),
        "feature_cols": list(feature_cols),
        # Save scaler state for future inference.
        "scaler_min_": scaler.min_.astype(np.float32),
        "scaler_scale_": scaler.scale_.astype(np.float32),
        "family_names": list(FAMILY_NAMES),
        "attack_names": list(ATTACK7_NAMES),
    },
    atk_model_path,
)
print(f"[Save] gate model   -> {gate_model_path}")
print(f"[Save] attack model -> {atk_model_path}")

# ===== 5) Hierarchical inference + threshold tuning + report =====
import numpy as np
import torch
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

if "ATTACK7_NAMES" not in globals():
    ATTACK7_NAMES = ["DoS", "DDoS", "BruteForce", "WebAttack", "Botnet", "PortScan"]
if "FAMILY_NAMES" not in globals():
    FAMILY_NAMES = ["Normal"] + ATTACK7_NAMES

BENIGN_ID = 0
N_FAMILY = len(FAMILY_NAMES)
N_ATTACK = len(ATTACK7_NAMES)


# -------------------------
# 5A) Collect probs
# -------------------------
@torch.no_grad()
def collect_attack_probs_nn(model: nn.Module, loader: DataLoader):
    model.eval()
    out = []
    for xb, _ in loader:
        xb = xb.to(device)
        probs = torch.softmax(model(xb), dim=1).cpu().numpy()
        out.append(probs)
    return np.concatenate(out, axis=0)


# Gate probs from row-level XGBoost on sequence last-step features.
X_val_gate = X_val_s[val_end_idx]   # [N, F]
X_test_gate = X_test_s[test_end_idx]

val_attack_prob = gate_model.predict_proba(X_val_gate)[:, 1]
test_attack_prob = gate_model.predict_proba(X_test_gate)[:, 1]

val_bin_probs = np.stack([1.0 - val_attack_prob, val_attack_prob], axis=1)   # [N,2]
test_bin_probs = np.stack([1.0 - test_attack_prob, test_attack_prob], axis=1)

# Attack probs on all windows (aligned to val_end_idx/test_end_idx order).
val_atk_probs = collect_attack_probs_nn(atk_model, full_val_loader)
test_atk_probs = collect_attack_probs_nn(atk_model, full_test_loader)

# Sequence GT family labels: normal=0, attack classes=1..N_ATTACK
y_val_family_seq = np.where(y_val_attack7_seq >= 0, y_val_attack7_seq + 1, 0).astype(np.int64)
y_test_family_seq = np.where(y_test_attack7_seq >= 0, y_test_attack7_seq + 1, 0).astype(np.int64)
y_val_bin_seq = (y_val_family_seq != 0).astype(np.int64)
y_test_bin_seq = (y_test_family_seq != 0).astype(np.int64)


# -------------------------
# 5B) Tune thresholds on VAL
# -------------------------
def bin_metrics(y_true_bin, y_pred_bin):
    tp = int(((y_true_bin == 1) & (y_pred_bin == 1)).sum())
    fn = int(((y_true_bin == 1) & (y_pred_bin == 0)).sum())
    fp = int(((y_true_bin == 0) & (y_pred_bin == 1)).sum())
    tn = int(((y_true_bin == 0) & (y_pred_bin == 0)).sum())
    dr = tp / (tp + fn + 1e-12)
    fpr = fp / (fp + tn + 1e-12)
    acc = (y_true_bin == y_pred_bin).mean()
    return {"DR": dr, "FPR": fpr, "ACC": acc, "tp": tp, "fn": fn, "fp": fp, "tn": tn}


def hierarchical_predict(bin_probs, atk_probs, gate_thr, joint_thr):
    p_attack = bin_probs[:, 1]
    atk_conf = atk_probs.max(axis=1)
    atk_pred = atk_probs.argmax(axis=1)  # 0..N_ATTACK-1
    joint = p_attack * atk_conf

    y_pred = np.zeros(len(p_attack), dtype=np.int64)  # default normal
    m = (p_attack >= gate_thr) & (joint >= joint_thr)
    y_pred[m] = atk_pred[m] + 1
    return y_pred, joint


def tune_thresholds(
    y_true_family,
    bin_probs,
    atk_probs,
    target_dr=0.90,
    target_fpr=0.03,
    gate_grid=np.linspace(0.10, 0.95, 86),
    joint_grid=np.linspace(0.10, 0.95, 86),
    topk=8,
):
    y_true_bin = (y_true_family != 0).astype(np.int64)

    cand = []
    best = None
    best_score = 1e18

    for g in gate_grid:
        for j in joint_grid:
            y_pred_family, _ = hierarchical_predict(bin_probs, atk_probs, float(g), float(j))
            y_pred_bin = (y_pred_family != 0).astype(np.int64)
            m = bin_metrics(y_true_bin, y_pred_bin)

            dr_under = max(0.0, target_dr - m["DR"])
            score = (1.8 * abs(m["FPR"] - target_fpr)) + (1.4 * abs(m["DR"] - target_dr)) + (6.0 * dr_under)

            cand.append((float(g), float(j), m, float(score)))
            if score < best_score:
                best_score = score
                best = (float(g), float(j), m, float(score))

    top = sorted(cand, key=lambda x: x[3])[:topk]

    print("\n[Hier Threshold Tuning on VAL (gate + joint)]")
    print(
        f"  chosen_gate_threshold={best[0]:.4f} | chosen_joint_threshold={best[1]:.4f} | "
        f"chosen_score={best[3]:.5f}"
    )
    print(
        f"  val_DR={best[2]['DR']*100:.2f}% | val_FPR={best[2]['FPR']*100:.2f}% | val_ACC={best[2]['ACC']*100:.2f}%"
    )
    print(f"  target_DR={target_dr*100:.2f}% | target_FPR={target_fpr*100:.2f}%")
    print("  top-threshold candidates:")
    for g, j, m, s in top:
        print(
            f"    g={g:.4f} | j={j:.4f} | score={s:.5f} | "
            f"DR={m['DR']*100:.2f}% | FPR={m['FPR']*100:.2f}% | ACC={m['ACC']*100:.2f}%"
        )
    return best[0], best[1]


gate_thr, joint_thr = tune_thresholds(
    y_true_family=y_val_family_seq,
    bin_probs=val_bin_probs,
    atk_probs=val_atk_probs,
    target_dr=GATE_TARGET_DR,
    target_fpr=GATE_TARGET_FPR,
)
print(f"[Hier] Apply thresholds: gate={gate_thr:.4f}, joint={joint_thr:.4f}")

# =========================
# 5B-2) Save runtime config (3: thresholds + artifact paths)
# =========================
runtime_cfg_path = CKPT_DIR / f"{RUN_TAG}_runtime_config.json"
runtime_cfg = {
    "run_tag": RUN_TAG,
    "gate_model_path": str(gate_model_path),
    "attack_model_path": str(atk_model_path),
    "gate_thr": float(gate_thr),
    "joint_thr": float(joint_thr),
    "seq_len": int(SEQ_LEN),
    "family_names": list(FAMILY_NAMES),
    "attack_names": list(ATTACK7_NAMES),
}
with open(runtime_cfg_path, "w", encoding="utf-8") as f:
    json.dump(runtime_cfg, f, ensure_ascii=False, indent=2)
print(f"[Save] runtime cfg  -> {runtime_cfg_path}")


# -------------------------
# 5C) Reports
# -------------------------
def per_class_ovr(y_true, y_pred, n_classes):
    out = []
    N = len(y_true)
    for c in range(n_classes):
        tc = (y_true == c)
        pc = (y_pred == c)
        tp = int((tc & pc).sum())
        fn = int((tc & ~pc).sum())
        fp = int((~tc & pc).sum())
        tn = int((~tc & ~pc).sum())
        out.append(
            {
                "class_id": c,
                "DR": tp / (tp + fn + 1e-12),
                "ACC": (tp + tn) / (N + 1e-12),
                "FPR": fp / (fp + tn + 1e-12),
                "tp": tp,
                "fn": fn,
                "fp": fp,
                "tn": tn,
            }
        )
    return out


def multiclass_metrics(y_true, y_pred):
    return {
        "ACC_micro": accuracy_score(y_true, y_pred),
        "Precision_macro": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "Recall_macro": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "F1_macro": f1_score(y_true, y_pred, average="macro", zero_division=0),
    }


def print_report(ds_name, y_true_family, y_pred_family):
    y_true_bin = (y_true_family != 0).astype(np.int64)
    y_pred_bin = (y_pred_family != 0).astype(np.int64)

    bm = bin_metrics(y_true_bin, y_pred_bin)
    pc = per_class_ovr(y_true_family, y_pred_family, N_FAMILY)
    mc = multiclass_metrics(y_true_family, y_pred_family)

    print("\n" + "=" * 92)
    print(f"Dataset: {ds_name}")
    print("=" * 92)
    print(f"{'Class':<14}{'DR':>10}{'ACC':>10}{'FPR':>10}{'TP':>8}{'FN':>8}{'FP':>8}{'TN':>8}")
    print("-" * 92)
    for m in pc:
        cname = FAMILY_NAMES[m["class_id"]]
        print(
            f"{cname:<14}"
            f"{m['DR']*100:9.2f}%"
            f"{m['ACC']*100:9.2f}%"
            f"{m['FPR']*100:9.2f}%"
            f"{m['tp']:8d}{m['fn']:8d}{m['fp']:8d}{m['tn']:8d}"
        )
    print("-" * 92)
    print(
        f"{'OVERALL(bin)':<14}"
        f"{bm['DR']*100:9.2f}%"
        f"{bm['ACC']*100:9.2f}%"
        f"{bm['FPR']*100:9.2f}%"
        f"{bm['tp']:8d}{bm['fn']:8d}{bm['fp']:8d}{bm['tn']:8d}"
    )
    print("=" * 92)
    print(
        f"[{N_FAMILY}-class] ACC_micro={mc['ACC_micro']*100:.2f}% | "
        f"Precision_macro={mc['Precision_macro']*100:.2f}% | "
        f"Recall_macro={mc['Recall_macro']*100:.2f}% | "
        f"F1_macro={mc['F1_macro']*100:.2f}%"
    )
    return bm, mc


# -------------------------
# 5D) Final inference
# -------------------------
y_val_pred_family, _ = hierarchical_predict(val_bin_probs, val_atk_probs, gate_thr, joint_thr)
y_test_pred_family, _ = hierarchical_predict(test_bin_probs, test_atk_probs, gate_thr, joint_thr)

val_bm, val_mc = print_report("Validation", y_val_family_seq, y_val_pred_family)
test_bm, test_mc = print_report("Test", y_test_family_seq, y_test_pred_family)


# ===== 6) Quick diagnostics: Gate-only vs ATK-only =====
# ---------- A) Gate-only on VAL/TEST ----------
val_gate_pred_bin = (val_bin_probs[:, 1] >= gate_thr).astype(np.int64)
test_gate_pred_bin = (test_bin_probs[:, 1] >= gate_thr).astype(np.int64)


def print_bin_diag(name, y_true_bin, y_pred_bin):
    tp = int(((y_true_bin == 1) & (y_pred_bin == 1)).sum())
    fn = int(((y_true_bin == 1) & (y_pred_bin == 0)).sum())
    fp = int(((y_true_bin == 0) & (y_pred_bin == 1)).sum())
    tn = int(((y_true_bin == 0) & (y_pred_bin == 0)).sum())
    dr = tp / (tp + fn + 1e-12)
    fpr = fp / (fp + tn + 1e-12)
    acc = (y_true_bin == y_pred_bin).mean()
    print(f"\n[Gate-only | {name}]")
    print(f"ACC={acc*100:.2f}% | DR={dr*100:.2f}% | FPR={fpr*100:.2f}%")
    print(f"TP={tp}, FN={fn}, FP={fp}, TN={tn}")
    print("Confusion [[TN,FP],[FN,TP]]:")
    print(confusion_matrix(y_true_bin, y_pred_bin, labels=[0, 1]))


print_bin_diag("VAL", y_val_bin_seq, val_gate_pred_bin)
print_bin_diag("TEST", y_test_bin_seq, test_gate_pred_bin)


# ---------- B) ATK-only on attack samples ----------
@torch.no_grad()
def collect_nn_pred(model: nn.Module, loader: DataLoader):
    model.eval()
    ys, yh = [], []
    for xb, yb in loader:
        xb = xb.to(device)
        pred = torch.argmax(model(xb), dim=1).cpu().numpy().astype(np.int64)
        ys.append(yb.numpy().astype(np.int64))
        yh.append(pred)
    return np.concatenate(ys), np.concatenate(yh)


y_val_atk_true, y_val_atk_pred = collect_nn_pred(atk_model, atk_val_loader)
y_test_atk_true, y_test_atk_pred = collect_nn_pred(atk_model, atk_test_loader)

print("\n[ATK-only | VAL]")
print(
    f"ACC={accuracy_score(y_val_atk_true, y_val_atk_pred)*100:.2f}% | "
    f"Macro-F1={f1_score(y_val_atk_true, y_val_atk_pred, average='macro', zero_division=0)*100:.2f}%"
)
print(confusion_matrix(y_val_atk_true, y_val_atk_pred, labels=list(range(N_ATTACK))))
print(
    classification_report(
        y_val_atk_true,
        y_val_atk_pred,
        labels=list(range(N_ATTACK)),
        target_names=ATTACK7_NAMES,
        zero_division=0,
    )
)

print("\n[ATK-only | TEST]")
print(
    f"ACC={accuracy_score(y_test_atk_true, y_test_atk_pred)*100:.2f}% | "
    f"Macro-F1={f1_score(y_test_atk_true, y_test_atk_pred, average='macro', zero_division=0)*100:.2f}%"
)
print(confusion_matrix(y_test_atk_true, y_test_atk_pred, labels=list(range(N_ATTACK))))
print(
    classification_report(
        y_test_atk_true,
        y_test_atk_pred,
        labels=list(range(N_ATTACK)),
        target_names=ATTACK7_NAMES,
        zero_division=0,
    )
)


# ---------- C) Gate threshold sweep on TEST ----------
print("\n[Gate threshold sweep on TEST]")
for g in [0.50, 0.60, 0.70, 0.80, 0.90]:
    pred = (test_bin_probs[:, 1] >= g).astype(np.int64)
    tp = int(((y_test_bin_seq == 1) & (pred == 1)).sum())
    fn = int(((y_test_bin_seq == 1) & (pred == 0)).sum())
    fp = int(((y_test_bin_seq == 0) & (pred == 1)).sum())
    tn = int(((y_test_bin_seq == 0) & (pred == 0)).sum())
    dr = tp / (tp + fn + 1e-12)
    fpr = fp / (fp + tn + 1e-12)
    acc = (y_test_bin_seq == pred).mean()
    print(
        f"g={g:.2f} | ACC={acc*100:6.2f}% | DR={dr*100:6.2f}% | FPR={fpr*100:6.2f}% | "
        f"TP={tp:5d} FP={fp:5d} TN={tn:5d} FN={fn:5d}"
    )


# ===== 7) Reusable inference helpers (load + predict) =====
def load_gate_model(gate_json_path: str):
    m = XGBClassifier(objective="binary:logistic", eval_metric="logloss", n_jobs=-1)
    m.load_model(gate_json_path)
    return m


def load_attack_model(atk_pth_path: str, device_obj):
    ckpt = torch.load(atk_pth_path, map_location=device_obj)
    model = CNNLSTMHybrid(
        in_ch=int(ckpt["in_ch"]),
        n_classes=int(ckpt["n_classes"]),
        lstm_hidden=int(ckpt["lstm_hidden"]),
        lstm_layers=int(ckpt["lstm_layers"]),
        bidir=bool(ckpt["lstm_bidir"]),
        dropout=float(ckpt["dropout"]),
    ).to(device_obj)
    model.load_state_dict(ckpt["state_dict"])
    model.eval()
    return model, ckpt


def _scale_with_saved_state(X: np.ndarray, scaler_min: np.ndarray, scaler_scale: np.ndarray):
    # MinMaxScaler transform: X_scaled = X * scale_ + min_
    return X * scaler_scale + scaler_min


@torch.no_grad()
def _collect_attack_probs_from_end_idx(model, X_scaled: np.ndarray, end_idx: np.ndarray, seq_len: int, batch_size: int):
    ds = WindowDataset(X_scaled, end_idx, np.zeros(len(end_idx), dtype=np.int64), seq_len)
    ld = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY)
    out = []
    model.eval()
    for xb, _ in ld:
        xb = xb.to(device)
        out.append(torch.softmax(model(xb), dim=1).cpu().numpy())
    return np.concatenate(out, axis=0)


def predict_from_dataframe(df_new: pd.DataFrame, gate_json_path: str, atk_pth_path: str, runtime_json_path: str):
    with open(runtime_json_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    gate = load_gate_model(gate_json_path)
    atk, ckpt = load_attack_model(atk_pth_path, device)

    seq_len = int(cfg["seq_len"])
    gate_thr_local = float(cfg["gate_thr"])
    joint_thr_local = float(cfg["joint_thr"])
    feat_cols = list(ckpt["feature_cols"])
    scaler_min = np.asarray(ckpt["scaler_min_"], dtype=np.float32)
    scaler_scale = np.asarray(ckpt["scaler_scale_"], dtype=np.float32)

    xdf = df_new.copy()
    xdf.columns = xdf.columns.str.strip()
    for c in feat_cols:
        if c not in xdf.columns:
            xdf[c] = 0.0
    xdf = xdf[feat_cols]
    xdf = xdf.apply(pd.to_numeric, errors="coerce")
    X = xdf.to_numpy(dtype=np.float32)

    finite_mask = np.isfinite(X).all(axis=1)
    X = X[finite_mask]
    if len(X) < seq_len:
        raise ValueError(f"Not enough valid rows for sequence prediction: {len(X)} < seq_len={seq_len}")

    Xs = _scale_with_saved_state(X, scaler_min, scaler_scale).astype(np.float32)
    end_idx = np.arange(seq_len - 1, len(Xs), 1, dtype=np.int64)

    gate_probs = gate.predict_proba(Xs[end_idx])
    atk_probs = _collect_attack_probs_from_end_idx(atk, Xs, end_idx, seq_len, BATCH_T)

    y_pred_family, joint = hierarchical_predict(gate_probs, atk_probs, gate_thr_local, joint_thr_local)
    fam_names = cfg["family_names"]
    pred_names = [fam_names[i] for i in y_pred_family]

    out = pd.DataFrame(
        {
            "end_row_idx": end_idx,
            "pred_family_id": y_pred_family,
            "pred_family_name": pred_names,
            "p_attack": gate_probs[:, 1],
            "atk_conf": atk_probs.max(axis=1),
            "joint_score": joint,
        }
    )
    return out
